<a href="https://colab.research.google.com/github/RockNCode/notebooks/blob/main/UdemyTensorFlow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)


2.8.2


In [2]:
hello = tf.constant("Hello ")
world = tf.constant("World")

type(hello)

tf.print(hello+world)

Hello World


In [3]:

a = tf.constant(10)
b = tf.constant(20)

c = a+b

tf.print(c)

30


In [4]:
tf.fill((4,4),10)


<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]], dtype=int32)>

In [5]:
zeros = tf.zeros((4,4))


In [6]:
ones = tf.ones((4,4))

In [7]:
myrandn = tf.random.normal((4,4),mean=0.0,stddev=1.0)
myrandn


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.0797934 , -0.2738042 ,  0.03152259,  0.30559286],
       [-0.8605339 , -1.9971837 , -1.0447905 ,  1.098707  ],
       [-1.6190565 , -2.3925629 ,  1.5371269 , -0.51404506],
       [ 0.450503  ,  1.3884885 , -0.0420259 ,  1.364144  ]],
      dtype=float32)>

In [8]:
myrandu = tf.random.uniform((4,4),minval=0,maxval=1)
myrandu


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.5635432 , 0.33273435, 0.8811182 , 0.80833375],
       [0.11942017, 0.99203694, 0.7286563 , 0.7819464 ],
       [0.36696076, 0.68207955, 0.05808318, 0.48853326],
       [0.37445414, 0.12207246, 0.69690776, 0.6528609 ]], dtype=float32)>

In [9]:
myops = [zeros,ones, myrandn,myrandu]

for op in myops:
  op
  tf.print(op)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[0.0797934 -0.273804188 0.0315225869 0.305592865]
 [-0.860533893 -1.99718368 -1.04479051 1.09870696]
 [-1.61905646 -2.39256287 1.5371269 -0.51404506]
 [0.450503 1.38848853 -0.0420258977 1.36414397]]
[[0.5635432 0.332734346 0.881118178 0.808333755]
 [0.119420171 0.992036939 0.728656292 0.781946421]
 [0.366960764 0.682079554 0.0580831766 0.488533258]
 [0.374454141 0.122072458 0.696907759 0.65286088]]


In [12]:
a = tf.constant([[1,2],
                 [3,4]])
a.get_shape()


TensorShape([2, 2])

In [16]:
b = tf.constant([[10],[100]])
b.get_shape()


TensorShape([2, 1])

In [17]:
res_mult = tf.matmul(a,b)
tf.print(res_mult)

[[210]
 [430]]
