<a href="https://colab.research.google.com/github/RockNCode/notebooks/blob/main/udemy_tf_graphs2_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [6]:
mytensor = tf.random.uniform((4,4),0,1)
mytensor

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.83810866, 0.10333312, 0.66899824, 0.06173074],
       [0.24430275, 0.7859026 , 0.18834996, 0.98322797],
       [0.28895223, 0.20264828, 0.13047314, 0.02763188],
       [0.94008636, 0.5112734 , 0.98115194, 0.2740997 ]], dtype=float32)>

In [9]:
myvar = tf.Variable(initial_value=mytensor)
myvar

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[0.83810866, 0.10333312, 0.66899824, 0.06173074],
       [0.24430275, 0.7859026 , 0.18834996, 0.98322797],
       [0.28895223, 0.20264828, 0.13047314, 0.02763188],
       [0.94008636, 0.5112734 , 0.98115194, 0.2740997 ]], dtype=float32)>

In [ ]:
ph= tf